"""Added BuyLimitOrder and SellLimitOrder, removed Threshold

Revision ID: 97822c6f1f19
Revises: 9dcdf0e267d5
Create Date: 2024-08-25 22:15:11.599624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97822c6f1f19'
down_revision = '9dcdf0e267d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
