"""Added BuyLimitOrder and SellLimitOrder, removed Threshold

Revision ID: 9dcdf0e267d5
Revises: 3df208c08b8f
Create Date: 2024-08-25 22:04:30.310521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcdf0e267d5'
down_revision = '3df208c08b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_limit_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('buy_limit_orders_stock_symbol_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stocks', ['stock_id'], ['id'])
        batch_op.drop_column('stock_symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_limit_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_symbol', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('buy_limit_orders_stock_symbol_fkey', 'stocks', ['stock_symbol'], ['id'])
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###
