"""Create thresholds table

Revision ID: ca5394461650
Revises: cf86ad129f50
Create Date: 2024-08-19 00:38:39.161585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5394461650'
down_revision = 'cf86ad129f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('buy_threshold', sa.Float(), nullable=False),
    sa.Column('sell_threshold', sa.Float(), nullable=False),
    sa.Column('buy_quantity', sa.Float(), nullable=False),
    sa.Column('sell_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thresholds')
    # ### end Alembic commands ###
